name: "Build & Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #pin v4.1.2

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #pin v5.0.1
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
